### ISSUE TITLE
EdgeTX - voice synchronization

### ISSUE THREAD

**Issue by ZS-Man** [Mattoia90/F3K_Training#1]
Hi,
until now I've been using this script on X10s with OpenTX without any problem.
Now I switched to EdgeTX and I have two problems:
1. slow and jerky movement when selecting a task (but that's not important)
2. after confirming any task, during 16s of preparation, the countdown on the display and the voice countdown are not synchronized. The voice countdown is slow. Same problem with countdown on flight end.

EdgeTX 2.6.0 and 2.7-nightly, in radio and simulator the same problem.

Is there any update needed for EdgeTX?

Thank you.

**Comment by Mattoia90** [comment]
Hi, No sorry, I haven't a EdgeTx radio's for test this scritp, sorry.
In my opinion this would appear to be a hardware/firmware radio problem or audio codec compatibility.
All the opentx tested works well.

**Comment by ZS-Man** [comment]
Hi, problem solved.
https://github.com/EdgeTX/edgetx/issues/1805

The problem is longer sound files in edgetx.

F3k Training now works great again.
Thanks.

**Comment by Mattoia90** [comment]
Thank you for the update.
