### ISSUE TITLE
Task B doesn't start in latest version

### ISSUE THREAD

**Issue by 00steven** [Mattoia90/F3K_Training#7]
**Describe the bug**
Task B 10 min and 7 min don't start in the latest version

**Comment by agibson2** [comment]
Thanks for reporting that.  I just updated the code to fix this.  Check latest version 6.3.6.  I left an end statement in the B task's view_b.lua file which broke the code for the B tasks.

**Comment by agibson2** [comment]
It looks like you reported this on the wrong F3K_Training.  This is the one for OpenTX that Mattoia90 is maintaining.

This is likely the one you are referring to and I fixed it in the next release 6.3.6.
https://github.com/agibson2/F3K_Training

**Comment by Mattoia90** [comment]
I tested Task B both for 7 and 10 minutes, and it works correctly on the Taranis X-Lite. Can you confirm that it's the Ethos repository so we can close the issue? Thanks.

**Comment by Mattoia90** [comment]
I test the Task B on Taranis X9D and work fine.
