### ISSUE TITLE
Failing to detect correct OS version when version passes v2.9

### ISSUE THREAD

**Issue by gantonjo-tnm** [Mattoia90/F3K_Training#9]
On RadioMaster TX16S with EdgeTX 2.10 the widget fails to start. Investigation shows that way of detecting version is cause of the problem:

From [opentx_srv.lua](https://github.com/Mattoia90/F3K_Training/blob/main/F3K_TRAINING/opentx_srv.lua), I found that using string.sug(ver,1,3) only selects 3 leftmost characters of the version number, resulting in detection of version 2.1 instead of version 2.10.

```
ok, msg = pcall( function()
	local ver = getVersion()
	print("Read version "..ver)
	if type( ver ) == 'string' then
		local ver = string.sub( ver, 1, 3 )
		if ver == '2.0' then
			--print( 'F3K: OpenTX Version Detected = 2.0' )
			runningTwoPointZero()
		elseif ver == '2.1' then
			--print( 'F3K: OpenTX Version Detected = 2.1' )
			runningTwoPointOne()
		elseif ver == '2.2' then
			--print( 'F3K: OpenTX Version Detected = 2.2' )
			runningTwoPointTwo( widget )
		else
			--print( 'F3K: OpenTX Version >= 2.3 assumed' )
			runningTwoPointThree( widget )
		end
	end
end )
```

I have solved this on my radio by simply changing the code as follows:

```
ok, msg = pcall( function()
	local ver = getVersion()
	print("Read version "..ver)
	if type( ver ) == 'string' then
		local ver = string.sub( ver, 1, 4 )
		if ver == '2.0' then
			--print( 'F3K: OpenTX Version Detected = 2.0.' )
			runningTwoPointZero()
		elseif ver == '2.1' then
			--print( 'F3K: OpenTX Version Detected = 2.1.' )
			runningTwoPointOne()
		elseif ver == '2.2' then
			--print( 'F3K: OpenTX Version Detected = 2.2.' )
			runningTwoPointTwo( widget )
		else
			--print( 'F3K: OpenTX Version >= 2.3 assumed' )
			runningTwoPointThree( widget )
		end
	end
end )
```

Maybe not the best solution for a long run, but is least impact on other parts of the code ;-) Ok, I see that it will not detect versions 2.x without any minor version numbers correctly, so you might like to improve on my simple solution.

Maybe using the match function to extract the version number parts would be better solution over all:

```
local major, minor, patch = ver:match("^(%d+)%.(%d+)%.?(%d*)$")

-- Convert major and minor to numbers
major = tonumber(major)
minor = tonumber(minor)
```

Then check for major and minor versions in the if parts. This I have not tested on my radio, so feel free to use it if you see it feasible.

**Comment by Mattoia90** [comment]
Hi, thanks for your feedback and the resolution options. I have implemented the one with the match function, which seems appropriate to me. I have already uploaded the commit to the repository; could you please test it on your radio? Unfortunately, I don't have a radio with that version available. Let me know, thank you very much.

**Comment by Mattoia90** [comment]
Hi, I think that with the latest commit the problem is resolved
